version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mega_secret
      MYSQL_DATABASE: deine_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
